spring.application.name=intern-management
server.port=8080

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/intern_management
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=tWTROdmHiRj4CMXibfZiAATnL94NB5r8vCEzzoCNy4m
jwt.expiration=3600000

# SQL Initialization (reset & load sequences correctly)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:truncate.sql
spring.sql.init.data-locations=classpath:data.sql


